# Stage 1 - build the application
FROM golang:1.22 AS builder

WORKDIR /app

COPY main.go .

RUN go build -o app main.go


# Stage 2 - small runtime image
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/app .

EXPOSE 8080

CMD ["./app"]